baseURL = 'https://silicon-safari.github.io/'
languageCode = 'en-us'
title = 'The Silicon Safari'
theme = 'anatole'
author = "alanturrr_1703"
description = "I like to write about software, system design, devops, ML and AI"
profilePicture = "images/profile.jpg"
